### ISSUE TITLE
Adding Golanci-lint Github Action and refactoring code for linters

### ISSUE THREAD

**Issue by ozerovandrei** [terraform-provider-openstack/terraform-provider-openstack#1063]
We should use http://golangci-lint.run to check the provider code against lots of useful Go linters.
This project is used by lots of other providers as well as other Go projects.

We can add the Github Action workflow: https://golangci-lint.run/usage/install#github-actions

Lots of code should be refactored to fix most linters issues.

**Comment by dkder3k** [comment]
Due to deprecation of maligned and interfacer linters should we disable them?
Latest versions of golangci-lint show corresponding warnings.
```
WARN [runner] The linter 'maligned' is deprecated due to: The repository of the linter has been archived by the owner. Use govet 'fieldalignment' instead. 
WARN [runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner.
```
There is [a suggestion](https://github.com/golangci/golangci-lint/issues/541#issuecomment-790929096) to replace maligned with fieldalignment but for interfacer there is no any replacement afaik

**Comment by ozerovandrei** [comment]
> Due to deprecation of maligned and interfacer linters should we disable them?
I don't see why we should use deprecated linters.
We can also run `golangci-lint linters` in the new version to see which linters do we need or not.
I guess that we need most of them to simplify PR reviews.
