### ISSUE TITLE
feature request: support for FWaaS v2.0

### ISSUE THREAD

**Issue by Crapworks** [terraform-provider-openstack/terraform-provider-openstack#115]
Hi there,

my OpenStack provider only supports FWaaS v2.0, the v1.0 endpoint is disabled. Are there any plans already to add support for FWaaS v2.0 since v1.0 is flagged as deprecated?

Cheers,
Christian

**Comment by fatmcgav** [comment]
@Crapworks I've had a quick look, and currently Gophercloud doesn't support FWaaS v2. 

Therefore support will need to be added to Gophercloud before we can add support into TF.

**Comment by Crapworks** [comment]
@fatmcgav Got it, I've created an issue there: https://github.com/gophercloud/gophercloud/issues/514

**Comment by jtopjian** [comment]
@Crapworks Just a heads up that this might take a number of weeks/months to put in place since the entirety of FWaaS v2 will have to be added to Gophercloud first. That's not to say it won't ever happen, but I just wanted to give you a realistic expectation.

**Comment by Crapworks** [comment]
@jtopjian Thanks for the estimation. I justed wanted it to be on the list, since I haven't seen anyone requesting it yet. Now I have something to track it :)

**Comment by khdegraaf** [comment]
FYI, I have mostly working code in my private branch for gophercloud at https://github.com/khdegraaf/gophercloud, and the matching code for Terraform in https://github.com/khdegraaf/terraform-provider-huaweicloud.  Note this is currently only targeting older production Huawei cloud variants like OTC, but I also plan to do PRs for the official OpenStack variants once I am comfortable with its status and have some time to do so.  See my comments on the GopherCloud feature request on one issue I am currently stuck on.  Although I think the code may work if you are running current versions of OpenStack.  Any help or pointers on how to properly create an "ACTIVE" router port I can attach to a firewall group on OTC would be appreciated.

**Comment by khdegraaf** [comment]
So everything about this appears to be working, other than linking the ports to the firewall group.  Since I had been testing against Huawei/OTC, I thought I would verify everything about my test setup and config was OK, so I ran the test-infra/standard/files/deploy.sh to get an OpenStack setup on CentOS.  The test suite ran fine for everything (although it times out if only given two hours to run), except for TestAccFWFirewallV1_router_update and TestAccFWFirewallV1_router_remove which fail as the firewall never gets past PENDING_CREATE.  Am I missing something in the setup/config for acceptance tests?  This is the same problem I am running into in the FirewallV2 tests (albeit slightly modified steps for v2 association of ports).  Since these additions are recent (May 16, 2017) by @fatmcgav and reviewed by @jtopjian, if you guys could comment on how that should work (and if it should be working), it would be really appreciated.

**Comment by jtopjian** [comment]
@khdegraaf Thanks for your work on this

> although it times out if only given two hours to run

For the entire suite? This sounds right - depending on the testing environment, this can vary. It takes around 90m to complete in AWS on an m3.xlarge instance.

> except for TestAccFWFirewallV1_router_update and TestAccFWFirewallV1_router_remove which fail as the firewall never gets past PENDING_CREATE. Am I missing something in the setup/config for acceptance tests? 

These tests are both passing in the standard acceptance test environment, so I'm not sure what the problem could be off the top of my head.

If you haven't already, it might be worthwhile to run these two tests by themselves in a clean environment to make sure another test didn't cause them to fail.

**Comment by khdegraaf** [comment]
> These tests are both passing in the standard acceptance test environment, so I'm not sure what the problem could be off the top of my head.

OK, good to know.  I am running them in KVM with a bridged network, so maybe that is a problem?  I saw your AWS setup script, maybe I need to see if I can get it approved to use that instead of using our local server.  Do you know what environments others test with besides AWS?

> If you haven't already, it might be worthwhile to run these two tests by themselves in a clean environment to make sure another test didn't cause them to fail.

I tried that and it still fails, so I am guessing maybe something about my network is the problem?  Any ideas on other setups that would work besides AWS?

**Comment by jtopjian** [comment]
Any environment should work. The key is using RDO to install an all-in-one environment isolated in a virtual machine. As long as you have that, everything should work. The "outer" networking (meaning, the network setup of the hypervisor) shouldn't matter. Shouldn't, but who knows.

Along with AWS, I also test within an OpenStack environment I have at work - but with an isolated virtual machine. Occasionally I will run some tests against the actual production cloud, but not the entire suite.

**Comment by khdegraaf** [comment]
So the complete acceptance test runs for you when running in OpenStack on an isolated virtual machine?  Are you running ocata like in deploy.sh, or something else?  Also, when you say you are using RDO, could you be specific about which project you are using?  https://www.rdoproject.org/ mentions three different ways to setup.  If you are using a particular script to setup, a pointer would be helpful.  It looks like you are using the packstack script from https://www.rdoproject.org/install/packstack/ inside of deploy.sh, but I wanted to be sure (and it is a bit out of date  using ocata rather than pike).

**Comment by khdegraaf** [comment]
Looks like you answered everything but my first question at https://github.com/gophercloud/gophercloud/issues/543.

**Comment by jtopjian** [comment]
> So the complete acceptance test runs for you when running in OpenStack on an isolated virtual machine?

Yes. 

I'll also try to combine both discussions here :smile: 

A few items that might help clarify things:

1. Terraform tests are run nightly on HashiCorp's CI system. The tests use a pre-made AMI that has Ocata already installed. This is to reduce the amount of time needed to get the environment up and running as well as to make sure we don't start testing on Pike+ until we're ready. I'll be documenting how to make an AMI (or a qcow) soon.

There are a handful of tests (39/168) that are not tested nightly. These are obvious ones like BlockStorage v1 and LBaaS v1 since they're deprecated. Tests that require the admin user are also ignored right now since a second test step needs added to switch users.

By using the standard `GNUMakefile` in the Terraform repo, these ignored tests are automatically accounted for:

```shell
$ make testacc TEST=./openstack
```

As of 1 hour ago, all tests are passing in CI :smile: 

2. For ad-hoc testing (before I approve or push a commit), I have the exact same environment running, built using a PackStack all-in-one environment. 

3. The all-in-one has some changes made to the answer file, but nothing major. Mostly just turning off Horizon and things like that. No custom network configuration.

4. For Gophercloud, tests are run in the same environment, but there is not a method to run all Gophercloud tests at once. There's a script in the `script` directory, but I've never used it and I don't think it works. Getting that working is something on my todo (getting the nightly Teraform testing working took me ~3 months off and on).

5. The same environment variables needed to test Terraform can also be used in Gophercloud. This is not a coincidence :)

Let me know if you have any other questions -- I'm happy to answer.

**Comment by khdegraaf** [comment]
Yes, I can verify that the script in 

`./script/acceptancetest`

(at least not for me)  I did use the line

`go test -v -tags "fixtures acceptance" -run "$1" github.com/gophercloud/gophercloud/acceptance/openstack/$2`

from README.md to run tests in a specific directory.  Is that what you are using?

**Comment by jtopjian** [comment]
@khdegraaf Yes, where `$1` can be any string match against a test:

`TestServers`
`TestServersCreateDestroy`
`TestServersCreateDestroyWithExtensions`

etc

So while there are some broken acceptance tests, you can still test against chunks at a time. At some point (soon, hopefully), I'd like to get Gophercloud in a state where the entire suite passes. A lot of that work will be in some of the services that I don't work with day-to-day (db, orchestration).

**Comment by khdegraaf** [comment]
Just to update current status.  This is working completely in my current private provider at https://github.com/khdegraaf/terraform-provider-opentelekomcloud.  When to merge it into official OpenStack provider is being actively discussed by various parties.

**Comment by Elethiomel** [comment]
Started working on this Upstream. Starting work on the provider feature now too

**Comment by MPV** [comment]
@Elethiomel / @pierreprinetti Did you arrive anywhere on this?

**Comment by Elethiomel** [comment]
I'm afraid that due to the deprecation of FWaaS in Openstack, I can no longer devote work time to this :(

**Comment by falencastro** [comment]
> I'm afraid that due to the deprecation of FWaaS in Openstack, I can no longer devote work time to this :(

Just a heads-up that FWaaS has been revived some weeks ago https://opendev.org/openstack/neutron-fwaas/commit/a9f26b81e28359e6ccacf95a97557ad3005adc5f
