### ISSUE TITLE
Error with network quotas with 1.38

### ISSUE THREAD

**Issue by jbe-dw** [terraform-provider-openstack/terraform-provider-openstack#1184]
### Terraform Version
version 0.13.5

### Affected Resource(s)
openstack_networking_quota_v2

### Terraform Configuration Files
```hcl
resource "openstack_networking_quota_v2" "quotaset_network" {
  project_id          = openstack_identity_project_v3.project.id
  floatingip          = var.quota_network.floating_ips
  network             = var.quota_network.networks
  port                = var.quota_network.ports
  rbac_policy         = var.quota_network.rbac_policies
  router              = var.quota_network.routers
  security_group      = var.quota_network.security_groups
  security_group_rule = var.quota_network.security_group_rules
  subnet              = var.quota_network.subnets
  subnetpool          = var.quota_network.subnetpools
}

```

### Debug Output
https://gist.github.com/jbe-dw/8a98b52edfa759b68521642e508ca37c

### Expected Behavior
Apply done correctly

### Actual Behavior
Error: Error parsing ID of openstack_networking_quota_v2 11d02006d0814b2fa6aa2ba6bf8177a4: Unable to determine networking quota ID 11d02006d0814b2fa6aa2ba6bf8177a4

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### Important Factoids
Run within a CI (docker debian10 image)

### References
None

**Comment by jbe-dw** [comment]
Hi,

This bugs occurs in all CI but not on my laptop (using the same terraform version). Fixing the provider to 1.37 works though.

I don't know what cause the bug.

Regards

**Comment by nikParasyr** [comment]
Hi are you passing the plan output from one ci stage to another?

**Comment by jbe-dw** [comment]
Yes, it is kept as an artifact

**Comment by nikParasyr** [comment]
I see from that the gist has `openstack_compute_quotaset_v2` and nova related things, except the error. I expect this due to wrong copy or something.

This was introduced due to: https://github.com/terraform-provider-openstack/terraform-provider-openstack/pull/1177

I'm trying to replicate this

**Comment by nikParasyr** [comment]
The only way I found to replicate this is when both are true:
- planfile is used
- planfile is made on 1.37.0 or earlier and apply with 1.38.0

@jbe-dw Could you please check/verify if your planfile was created with 1.37.0 or previous and then apply was 1.38.0?

When plan and apply are on 1.38 it works just fine, with and without a planfile.

---
@ozerovandrei I'm not sure how to tackle this. This seems like an edge-case that i did not foresee. I guess changing to accept both project_id and project_id/region as resource id will resolve this edge case but i think it will introduce different ones. Let me know what you think is a good way to resolve this. For the time being a changed related PRs to draft.

**Comment by ozerovandrei** [comment]
As far as I understand we don't handle the old ID format on update stage: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_quota_v2.go#L254

Maybe we could handle it here and call `SetId` as in Read method?

**Comment by nikParasyr** [comment]
Yes true. i'll make a patch to add this in update. Since the update will do the same change as create: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/main/openstack/resource_openstack_networking_quota_v2.go#L153-L157
i'll make a func out of this in `util.go` as blockstorage and compute quota will use the same.

**Comment by jbe-dw** [comment]
@nikParasyr I think it's not true because in the same CI stage we do the init and the plan. The state file is stored in consul though.
I'm won't get back to work until monday but I can say that the stage start with an empty container, install terraform from a package, copy the git repository and make terraform init then plan. I can give more detail next week but unless I miss something with the CI chain it appears to me that it's not.
The plan is done to generate the discussion topic in gitlab, we don't go to the apply stage (apply is done when MR is accepted).

But as doing the plan from my desktop does not bug, you may be right. Isn't it suppose to do a Read first and update the ID to the new format in the state ? I've read the changes and I was expecting to enter the update condition but it's not.

**Comment by nikParasyr** [comment]
@jbe-dw We have a similar setup, that is why my mind went there.

> I can say that the stage start with an empty container, install terraform from a package, copy the git repository and make terraform init then plan.

Since it's an empty container `terraform init` will download the required provider (as there is nothing under `.terraform/` ). If you are not specifying the version of the provider it will download the latest. Logs will show which version was downloaded. 

> (apply is done when MR is accepted)

If your apply stage is similar as your plan, meaning empty container, install terraform from package, copy git repo and terraform init, terraform apply <planfile>, the terraform init will again download the provider, if version is not set then the latest will be download. Since opening an MR and merging can take days the provider version you use during plan and apply can be different (again if you are not setting the version of the provider).

>  Isn't it suppose to do a Read first and update the ID to the new format in the state?

When you provide a planfile terraform doesn't do the Read at all as it uses the input from the planfile instead. If you do a apply without a planfile then it does the Read first. This is probably why when you run it from your laptop it worked just fine.

I'm just speculating here but this is what i expect to have happened. I'm curious what your logs will show in terms of the version in the plan phase and in the apply one. 

In any case the proposed PR, updates the Update function as well so it should resolve this :)

**Comment by jbe-dw** [comment]
Yes but it is the terraform plan that fails when we push updates on the branch when the MR is opened. It is failing when generating the plan (which the purpose is only to send the plan to gitlab MR discussion for validation). As far as I remember from the CI config, the apply stage does not use the plan from the previous stage, but just does the apply (but you're right it redownloads everything).

The logs attached (I've not uploaded the whole log for privacy purpose but I can do it later if needed) are from the plan and not the apply.

I hope I've been more clear about the issue.

For the Read function, it is executed when `terraform plan`, isn't it ?

**Comment by nikParasyr** [comment]
>  It is failing when generating the plan

sorry. should have checked your gist a bit more careful before jumping to conclusions. 

Then i'm a bit clueless how this occurred as Read is executed during plan, update is not. I did test this from 1.37 to 1.38 without issues... The only thing that comes to mind is maybe due to consul as backend, but ill have to check how d.setid works.

If you can provide more extended logs on monday that might be helpful. Thanks for your help

**Comment by nikParasyr** [comment]
I found the reason and i can also replicate. 

Checked the gist a bit more thoroughly and I noticed in your state file that `region: null`. I wasn't aware that it's even possible. It's possible that region is defined in the creds you used locally and not it the ci. Would still like to have a bit more extended logs around the networking quota. Thanks :)

In any case, i'll update the patch to include such scenarios
