### ISSUE TITLE
Blockstorage: Volume type missing QoS settings

### ISSUE THREAD

**Issue by fitbeard** [terraform-provider-openstack/terraform-provider-openstack#1212]
### Terraform Version
Terraform: v0.14.7
OpenStack provider: v1.40.0
OpenStack version: Ussuri/Victoria

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_blockstorage_volume_type_v3

### Existing configuration
```
openstack volume type show 8b5dbf6d-db1a-475b-8e69-2d57390a17bd
+--------------------+--------------------------------------+
| Field              | Value                                |
+--------------------+--------------------------------------+
| access_project_ids | None                                 |
| description        | None                                 |
| id                 | 8b5dbf6d-db1a-475b-8e69-2d57390a17bd |
| is_public          | True                                 |
| name               | standard                             |
| properties         | volume_backend_name='ceph-hdd'       |
| qos_specs_id       | fdcb3ada-2c50-4286-b58a-aa0ec2dac397 |
+--------------------+--------------------------------------+

terraform import module.openstack-test-cloud.openstack_blockstorage_volume_type_v3.volume_type 8b5dbf6d-db1a-475b-8e69-2d57390a17bd

terraform state show module.openstack-test-cloud.openstack_blockstorage_volume_type_v3.volume_type
# module.openstack-test-cloud.openstack_blockstorage_volume_type_v3.volume_type:
resource "openstack_blockstorage_volume_type_v3" "volume_type" {
    extra_specs = {
        "volume_backend_name" = "ceph-hdd"
    }
    id          = "8b5dbf6d-db1a-475b-8e69-2d57390a17bd"
    is_public   = true
    name        = "standard"
}
```

Related: https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1202

**Comment by fitbeard** [comment]
@nikParasyr thank you in advance.

**Comment by nikParasyr** [comment]
@fitbeard This will take some time and it's not on top of my priority.

The QoS association are completely different api calls as shown here: https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=#quality-of-service-qos-specifications-qos-specs. Gophercloud doesnt support them yet so that needs to be implemented there first, and then either add them on the volume_type resource or create a new resource for them, not sure yet which is better. 

I'll be working on this stuff, but mostly when i get some free time so it might take a couple months before it lands

**Comment by nikParasyr** [comment]
Related upstream ticket https://github.com/gophercloud/gophercloud/issues/2139

**Comment by m-yosefpor** [comment]
Having some resource like `openstack_blockstorage_volume_qos_v3` and an attribute in `openstack_blockstorage_volume_type_v3` like `qos_associate_id` is very useful.

**Comment by nikParasyr** [comment]
Hola.

`openstack_blockstorage_qos_v3` has been created in a previous PR and should be part of the next release. This will allow creating qos etc for cinder.

For the association I decided to make a new resource => `openstack_blockstorage_volume_qos_association_v3` for simplicity reasons and due to how the api works. If everything goes well this should be resolved soon and available in the next release
