### ISSUE TITLE
tags key/value pair

### ISSUE THREAD

**Issue by SBatais** [terraform-provider-openstack/terraform-provider-openstack#1336]
Hi there,

I would like to know if the provider openstack 1.44.0 is able to manage tags as key/value pair, and not only as simple strings

### Terraform Version
terraform v0.13.5
openstack 1.44.0

### Affected Resource(s)
openstack_compute_instance_v2

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
tags considered as key/value pair

### Actual Behavior
It seems that tags are as simple strings

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
I have discovered this during some tests related to the issue https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1306

**Comment by SBatais** [comment]
@qukuijin1989 : if you have more information about this, I let you add a comment

**Comment by nikParasyr** [comment]
hello. Sorry for the late reply. 

Most Openstack services (if not all) allow tags as a set of strings and not key/value pairs. I find it rather annoying myself
Since its not something that openstack itself does not do, its not a feature that we can offer as the provider.

A workaround I use is to add them as strings like this: "key::value", ... and then parse and split the list. It's not the best way but it is doable.

Ill close the ticket as we cannot support this, unless openstack changes the way it does it
