### ISSUE TITLE
openstack_containerinfra_nodegroup_v1 does not allow to set role

### ISSUE THREAD

**Issue by jan-di-cgm** [terraform-provider-openstack/terraform-provider-openstack#1427]
### Terraform Version
```
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.48.0
```

### Affected Resource(s)
- openstack_containerinfra_nodegroup_v1

### Terraform Configuration Files
```hcl
resource "openstack_containerinfra_nodegroup_v1" "worker" {
  for_each = { for group in var.worker_nodegroups : group.name => group }

  name           = each.value.name
  cluster_id     = openstack_containerinfra_cluster_v1.main.id
  image_id       = data.openstack_containerinfra_clustertemplate_v1.main.image
  // [...]

  role           = "test"

  // [...]
}
```

### Debug Output
```
╷
│ Error: Value for unconfigurable attribute
│ 
│   with module.cluster.openstack_containerinfra_nodegroup_v1.worker,
│   on ../path/to/file.tf line 32, in resource "openstack_containerinfra_nodegroup_v1" "worker":
│   32:   role           = "test"
│ 
│ Can't configure a value for "role": its value will be decided automatically
│ based on the result of applying this configuration.
```

### Expected Behavior
Terraform created a nodegroup, each node will have the role that is given via `role` attribute

### Actual Behavior
Terraform does not allow to set a role for the nodegroup and stops applying

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
-

### References
-

**Comment by nikParasyr** [comment]
Unfortunately, magnum hasn't documented the nodegroup api so its a bit hard to see whether its possible to set `role` on creation. From reading a bit the related code and links from this [MR](https://github.com/gophercloud/gophercloud/issues/1767) and the docs [here](https://docs.openstack.org/magnum/latest/user/#create-a-new-node-group) it seems to be possible to set this during creation. 

So i think the change should be quite straightforward although unfortunately we cannot test it now due to https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1413
