### ISSUE TITLE
Identity scope: export token_id attribute

### ISSUE THREAD

**Issue by kayrus** [terraform-provider-openstack/terraform-provider-openstack#638]
It could be useful to export the token_id of the auth scope:

```hcl
data "openstack_identity_auth_scope_v3" "scope" {
  name = "scope"
}

output "token" {
  value = "${data.openstack_identity_auth_scope_v3.scope.token_id}"
}
```

### Affected Resource(s)
- openstack_identity_auth_scope_v3

### Important Factoids

It can decrease an amount of extra API calls to the Keystone by underlying `local-exec` provisioners (openstack, neutron, etc CLIs) and especially useful for CLI tools, which don't support application credentials, or other auth methods. However I'm not sure how secure is it:

```diff
diff --git a/openstack/data_source_openstack_identity_auth_scope_v3.go b/openstack/data_source_openstack_identity_auth_scope_v3.go
index 5bb566e..ac849b2 100644
--- a/openstack/data_source_openstack_identity_auth_scope_v3.go
+++ b/openstack/data_source_openstack_identity_auth_scope_v3.go
@@ -62,7 +62,10 @@ func dataSourceIdentityAuthScopeV3() *schema.Resource {
                                Type:     schema.TypeString,
                                Computed: true,
                        },
-
+                       "token_id": {
+                               Type:     schema.TypeString,
+                               Computed: true,
+                       },
                        "roles": {
                                Type:     schema.TypeList,
                                Computed: true,
@@ -105,6 +108,8 @@ func dataSourceIdentityAuthScopeV3Read(d *schema.ResourceData, meta interface{})
        d.Set("user_domain_name", user.Domain.Name)
        d.Set("user_domain_id", user.Domain.ID)
 
+       d.Set("token_id", config.OsClient.TokenID)
+
        project, err := result.ExtractProject()
        if err != nil {
                return err
```

**Comment by kayrus** [comment]
Looks quite dangerous. Doesn't worth the effort.

**Comment by kayrus** [comment]
I thought things over, and here is a valid use case for third-party applications:

```hcl
resource "openstack_identity_application_credential_v3" "barbican" {
  name        = "barbican"
  description = "Barbican technical application credential"
  roles       = ["keymanager_viewer"]
  expires_at  = "${timeadd(timestamp(), "10m")}"            # valid for 10 minutes
}

data "openstack_identity_auth_scope_v3" "barbican_token" {
  application_credential_id     = "${openstack_identity_application_credential_v3.barbican.id}"
  application_credential_secret = "${openstack_identity_application_credential_v3.barbican.secret}"
  set_token_id                  = true
}

output "token" {
  value = "${data.openstack_identity_auth_scope_v3.barbican_token.token_id}"
}
```

**Comment by kayrus** [comment]
I've noticed a few issues:

* using provider aliases with overrode application_credential creds doesn't support terraform dependencies:

```hcl
resource "openstack_identity_application_credential_v3" "barbican" {
  name        = "barbican"
  description = "Barbican technical application credential"
  roles       = ["keymanager_viewer"]
  expires_at  = "${timeadd(timestamp(), "20m")}"            # valid for 10 minutes
 
  lifecycle = {
    ignore_changes = [
      "expires_at"
    ]
  }
}
 
provider "openstack" {
  alias = "ac"
  application_credential_id = "${openstack_identity_application_credential_v3.barbican.id}"
  application_credential_secret = "${openstack_identity_application_credential_v3.barbican.secret}"
}
 
data "openstack_identity_auth_scope_v3" "barbican_token" {
  name = "barbican_token"
  provider = "openstack.ac"
  set_token_id = true
}
```

If OS ENVs are used, the first `terraform apply` run will use ENV variables.

* `gophercloud/gophercloud/auth_options.go` prefers environment variables and setting `application_credential_id` won't have an effect. Moving the condition into the top level seems to fix the issues. Another solution is to override auth options calling `openstack.Authenticate(client, *ao)` after the modified `ao`, but it looks more like a hack.

* If the application credential is expired, `terraform destroy` doesn't work, because the data source cannot be retrieved. there should be a workaround, which will return nil

**Comment by jtopjian** [comment]
I apologize, but I'm not totally following.

>  So it is better to switch computed fields to optional in the openstack_identity_auth_scope_v3 and use them to override provider auth.

I don't think so. `openstack_identity_auth_scope_v3` is meant to read the scope of the authentication from the `provider` block. I think you are trying to read a scope from another set of credentials which isn't supported by this data source.

With that in mind, does that clear things up?

**Comment by jtopjian** [comment]
In addition, if environment variables are getting in the way then there are two things to consider:

1. Having environment variables set when working with two sets of credentials will cause problems. I recommend unsetting environment variables entirely in this case.

2. Variable precedence for application credentials doesn't have as high priority as they should. For example, if an application ID and Secret should take precedence over a username and password, that should be reflected in `gophercloud/utils`. But I would suggest looking into the Python SDK to see how that works. If precedence is handled correctly, I'd advise going with Option 1.

But again, I could be misunderstanding something.

**Comment by kayrus** [comment]
Long story short. My aim is to use terraform to create an application credential with the limited role, then create a token from this application credential and forward this token to the chef automation as an argument.

From my perspective, the best candidate to implement this logic is `openstack_identity_auth_scope_v3`. Let me know if you think, that there should be a dedicated resource.

Nevertheless, if I want to dynamically set credentials for the provider, it could not be done easily, because of the dependency issue I mentioned above. And auth credentials have to be passed to the resource/data source directly.

**Comment by jtopjian** [comment]
Thanks! I think I understand now. And I think your idea is valid.

> From my perspective, the best candidate to implement this logic is openstack_identity_auth_scope_v3

Upon reviewing your example code, this should be fine. You're using an alias to create a separate provider block and then using `openstack_identity_auth_scope_v3` to obtain the auth scope. 

> Nevertheless, if I want to dynamically set credentials for the provider, it could not be done easily, because of the dependency issue I mentioned above.

Right. If I understand correctly, you're talking about when Terraform runs, the `provider` blocks are executed immediately. Since you want to generate credentials, you want to defer the second `provider` block from being executed.

A similar situation is when you want to create a virtual machine, provision it with MySQL and then us the MySQL provider to provision databases. The MySQL credentials won't be known until the virtual machine is created.

Using MySQL specifically, that provider accounts for this by doing "lazy loading" - maybe it has another term, but that's what I've called it. The MySQL provider block is still executed at the beginning of the apply, but an actual client isn't made until the last moment. This allows the interpolation to work.

Unfortunately, lazy loading comes with all sorts of bugs: namely concurrency issues. If we implemented lazy loading in this provider, it might require some breaking changes. If it didn't, it would still have the potential to introduce all sorts of bugs, so we'd have to deploy it when there was enough time to field any questions (which I'm a little swamped at the moment). That's not to say it's not possible to do - it's just a large thing to implement.

One alternative is to use the "local backend": https://www.terraform.io/docs/backends/types/local.html

You would have two Terraform directories (maybe this can be done in a single directory), one dependent on the other. The first directory would generate the credentials and then write them to state. The second directory would read in the state from the parent directory and fill in the `provider` block appropriately. I'm pretty sure I did this with the LXD provider a while back before I implemented lazy loading for it.

Let me know if this makes sense or if I'm totally off.

**Comment by kayrus** [comment]
@jtopjian it does make sense, but I'd prefer to develop an "elegant" hack rather than a dirty hack. Adding an ability to override auth credentials for the `openstack_identity_auth_scope_v3` data source sounds sane for me.

In addition, it would be great to revoke the token / credentials once the job is finished.

I'm open to suggestions.

**Comment by jtopjian** [comment]
Perhaps I misunderstood.

> From my perspective, the best candidate to implement this logic is openstack_identity_auth_scope_v3

I assumed you meant in the case where deferring execution of the provider block was possible.

My opinion that the `openstack_identity_auth_scope_v3` data source should be restricted to the credentials of the `provider` block still stands. The reasons is because there's a tight coupling between the `provider` block and this data source: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/data_source_openstack_identity_auth_scope_v3.go#L93-L100. If you wanted to add computed fields, you break that simplicity and open the door to all sorts of edge cases (as well as overlap with `provider`).

But application credentials can be different. Application credentials are a set of credentials created by a user, similar to a user creating an instance or network. And we have a resource for that: `openstack_identity_application_credential_v3`.

I'm assuming you need to generate a token because Chef can't authenticate using the generated application credentials? What if `openstack_identity_application_credential_v3` optionally generated a token? Or what if there was a `openstack_identity_application_credential_v3` data source which was specifically for application credential auth scopes?

**Comment by jtopjian** [comment]
> In addition, it would be great to revoke the token / credentials once the job is finished.

Thinking about this more: if you wanted to control the full lifecycle of an application credential (such as expiration?) then a resource is probably the best way to go.

Let's say `openstack_identity_application_credential_v3` had the ability to create a token along with the ID and secret. You could then attach a provisioner to the resource to do your Chef provisioning. When that was done, you could trigger a targeted destroy on `openstack_identity_application_credential_v3` which would delete the credentials.

If you wanted more control over the token, then maybe a separate resource such as `openstack_identity_application_credential_token_v3` which only generate a token. This would allow the application credential to live longer than the token. But if application credentials can be disposable, then wrapping it all into `openstack_identity_application_credential_v3` might also work.

I think the important thing here with regard to design is to think of an Application Credential as a user-controlled resource like any other (instance, network) rather than a full authentication scope.

**Comment by kayrus** [comment]
> I assumed you meant in the case where deferring execution of the provider block was possible.

I meant both cases. Sorry for not being clear.

> I'm assuming you need to generate a token because Chef can't authenticate using the generated application credentials?

correct.

> Or what if there was a openstack_identity_application_credential_v3 data source

for the full lifecycle the resource is the best option.

> Let's say openstack_identity_application_credential_v3 had the ability to create a token along with the ID and secret.

what if we create `openstack_identity_token_issue_v3` and `openstack_identity_token_revoke_v3` resources? Then using the single `terraform apply` user will be able to issue and revoke the token within one run?

Considering the discussed above, we still have an issue with the overrode credentials mentioned in the https://github.com/gophercloud/utils/issues/84. And I suppose that the `OverrideFromEnv` bool option is the simplest solution for the problem.

**Comment by jtopjian** [comment]
> Sorry for not being clear.

No apologies needed! 

> what if we create openstack_identity_token_issue_v3 and openstack_identity_token_revoke_v3 resources?

I understand the goal, but it feels weird. Maybe look at the AWS provider to see if any IAM resources have the ability to do what you want?

> Considering the discussed above, we still have an issue with the overrode credentials mentioned in the gophercloud/utils#84. And I suppose that the OverrideFromEnv bool option is the simplest solution for the problem.

I'm still not completely understanding this part. Is this still related to working with multiple sets of credentials? If so, then environment variables should not be used to prevent this kind of problem.

Whether in this issue or in gophercloud/utils#84, can you explain how to reproduce this issue?

**Comment by kayrus** [comment]
> I'm still not completely understanding this part. Is this still related to working with multiple sets of credentials? If so, then environment variables should not be used to prevent this kind of problem.
> Whether in this issue or in gophercloud/utils#84, can you explain how to reproduce this issue?

Clear use case: uses uses env variables to auth against keystone. User uses `OS_*` environment variables. These variables are handled using the terraform helper: `DefaultFunc: schema.EnvDefaultFunc("OS_XXX", ""),`. This is clear.

Let's assume user want to override auth options, which are already set via env. User will put these options directly into the provider block, e.g:

```hcl
provider "openstack" {
  user_name = "foo"
  password = "bar"
}
```

Will it work? No, because `ao, err := clientconfig.AuthOptions(clientOpts)` overrides user defined options by options taken from env. Therefore the openstack provider code takes env variables twice: using terraform helpers and using [utils/openstack/clientconfig/requests.go](https://github.com/gophercloud/utils/blob/0bcc8e728cb54c9dce9ed46924688b817ab14f31/openstack/clientconfig/requests.go#L424..L541). Besides, there is no possibility in terraform to define env_prefix. I hope it is clear now.

**Comment by jtopjian** [comment]
> Will it work? No, because ao, err := clientconfig.AuthOptions(clientOpts) overrides user defined options by options taken from env. 

It only does this if the field is an empty string:

* https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/config.go#L126
* https://github.com/gophercloud/utils/blob/0bcc8e728cb54c9dce9ed46924688b817ab14f31/openstack/clientconfig/requests.go#L445-L449

If `user_name` is set in `provider`, then `clientconfig.AuthInfo.Username` is not an empty string and so the environment variable should never be used. This was already accounted for here: https://github.com/terraform-providers/terraform-provider-openstack/issues/434

**Comment by kayrus** [comment]
It should not, but env variables are still used. `clientconfig.AuthOptions` -> `v3auth` -> https://github.com/gophercloud/utils/blob/0bcc8e728cb54c9dce9ed46924688b817ab14f31/openstack/clientconfig/requests.go#L424..L541

**Comment by jtopjian** [comment]
I apologize, but I'm not able to reproduce:

```diff
diff --git a/vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go b/vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
index ad1c33d..4afc0b7 100644
--- a/vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
+++ b/vendor/github.com/gophercloud/utils/openstack/clientconfig/requests.go
@@ -2,6 +2,7 @@ package clientconfig

 import (
        "fmt"
+       "log"
        "os"
        "reflect"
        "strings"
@@ -442,8 +443,11 @@ func v3auth(cloud *Cloud, opts *ClientOpts) (*gophercloud.AuthOptions, error) {
                }
        }

+       log.Print("[DEBUG] FOO 1")
        if cloud.AuthInfo.Username == "" {
+               log.Print("[DEBUG] FOO 2")
                if v := os.Getenv(envPrefix + "USERNAME"); v != "" {
+                       log.Printf("[DEBUG] FOO 3: %s\n", v)
                        cloud.AuthInfo.Username = v
                }
        }
```

And given the following Terraform configuration:

```hcl
provider "openstack" {
  user_name = "foobar"
}

resource "openstack_compute_keypair_v2" "foo" {
  name = "foo"
}
```

Then running:

```shell
env | grep OS_USERNAME
OS_USERNAME=demo

terraform init

TF_LOG=DEBUG terraform plan 2>&1 | grep FOO
2019-03-22T18:50:00.778Z [DEBUG] plugin.terraform-provider-openstack: 2019/03/22 18:50:00 [DEBUG] FOO 1
```

**Comment by kayrus** [comment]
I updated my previous comment.

**Comment by jtopjian** [comment]
> UPD: it is applicable, when the username is not set, but application credential is set.

Right, so this is what I was talking about when using multiple sets of credentials and environment variables - you're going to run into cases like this. I suggest either not using environment variables or using `clouds.yaml` (which is where you can set the env prefix, too).

**Comment by kayrus** [comment]
I am ok with the clouds.yaml, but not users. What if we introduce Auth type parameter in the provider config? This option will be used as it is already used for the token Auth in utils repo code.

**Comment by jtopjian** [comment]
> I am ok with the clouds.yaml, but not users.

I think that's generalizing things. There are a lot of users who take advantage of clouds.yaml.

> What if we introduce Auth type parameter in the provider config? This option will be used as it is already used for the token Auth in utils repo code.

Considering `--os-auth-type` is a valid field in the `openstack` command-line tool, then it is applicable here, too.

**Comment by kayrus** [comment]
> I think that's generalizing things. There are a lot of users who take advantage of clouds.yaml.

from my perspective, if clouds.yaml supports this, then other auth option methods should be in sync with clouds. the amount of cases, which require compromises, should be as low as possible.

> Considering --os-auth-type is a valid field in the openstack command-line tool, then it is applicable here, too.

I'm happy, that we found a consensus. The plan to resolve auth problem looks quite clear now.

I'll think again on the token issue. But I'm not always agree, that something should be developed in AWS first. AWS is not OpenStack. Other providers have to have the freedom, but without the strong bigotry.

**Comment by jtopjian** [comment]
> from my perspective, if clouds.yaml supports this, then other auth option methods should be in sync with clouds

Just to be clear: there's a difference between what clouds.yaml can do and what a command-line client can do. An appropriate comparison is Terraform and the `openstack` command-line tool. 

Some things that clouds.yaml supports is not appropriate for a command-line tool. But having the command-line tool support clouds.yaml offers a bridge.

>  But I'm not always agree, that something should be developed in AWS first. AWS is not OpenStack.

I agree that AWS is not OpenStack, but the AWS provider has a much larger audience, so it's possible that the use-case has been discussed and thought out already. That's the only reason I reference it.  Replace AWS with the Google provider or Azure, etc. 

It's about doing due diligence before creating something that either has a niche use-case or bends Terraform in a way it should not be bent. I suggested for you to do this since you have been heavily active in submitting PRs. I am more than happy to do this work, though.

> Other providers have to have the freedom, but without the strong bigotry.

I'm not sure who you are calling a bigot, but that choice of word is offensive.

**Comment by MariaBiosciences** [comment]
Any updates on this? Would be an awesome feature!

**Comment by kayrus** [comment]
@MariaBiosciences I'd suggest to use application credentials auth https://docs.openstack.org/api-ref/identity/v3/?expanded=authenticating-with-an-application-credential-detail#authenticating-with-an-application-credential
This issue has some corner cases, which require discussion.
