### ISSUE TITLE
data openstack_identity_user_v3 not working in cunjunction with LDAP

### ISSUE THREAD

**Issue by lz006** [terraform-provider-openstack/terraform-provider-openstack#786]
Hello Together,

It seems that the data module "openstack_identity_user_v3" is not able to search for users which in turn come from a LDAP directory.

### Terraform Version
 Terraform v0.12.0
+ provider.openstack v1.19.0

### Affected Resource(s)
- openstack_identity_project_v3

### Expected Behavior
This block..
```
data "openstack_identity_user_v3" "user_1" {
  name = "myname"
  domain_id = "${data.openstack_identity_project_v3.domain.domain_id}"
}
```

should give access to ${data.openstack_identity_user_v3.user_1.id}

### Actual Behavior
"terraform plan" gives:

```
...

data.openstack_identity_role_v3.admin: Refreshing state...
data.openstack_identity_project_v3.domain: Refreshing state...
data.openstack_identity_user_v3.user_1: Refreshing state...

Error: Your openstack_identity_user_v3 query returned no results. Please change your search criteria and try again.

  on main.tf line 31, in data "openstack_identity_user_v3" "user_1":
  31: data "openstack_identity_user_v3" "user_1" {

```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create main.rf with content
```
provider "openstack" {
  tenant_name = "iaas4me"
  auth_url    = "http://ctl1.bla.bla.de:5000/v3"
  region      = "RegionOne"
  domain_name = "mydomain"
  user_domain_name = "mydomain"
  project_domain_name = "mydomain"
  
}

data "openstack_identity_project_v3" "domain" {
  name = "mydomain"
  is_domain = true
}

data "openstack_identity_role_v3" "admin" {
  name = "admin"
}

data "openstack_identity_user_v3" "user_1" {
  name = "myuser"
  domain_id = "${data.openstack_identity_project_v3.domain.domain_id}"
}

resource "openstack_identity_role_assignment_v3" "role_assignment_1" {
  **user_id = "${data.openstack_identity_user_v3.user_1.id}"**
  project_id = "123456"
  role_id = "${data.openstack_identity_role_v3.admin.id}"
  domain_id = "${data.openstack_identity_project_v3.domain.domain_id}"
}
```
2. run "terraform plan"

When I use openstack cli with same credentials (cloud) I'm able to find any user that orginally comes from bound LDAP directory.  (e.g. openstack user show --domain mydomain myuser )

Hoping someone could help me out.

Thanks!.

**Comment by dariko** [comment]
Hi, I was having the same problem, but after some debugging I found the problem is not with this provider.

Running the terraform command with `OS_DEBUG=1 TF_LOG=DEBUG` I found that the `GET` sent to keystone always includes a `enabled=<true|false>` parameter.

Trying to execute (with a valid token) these `GET`s in my environment:
```
https://<my_keystone_endpoint>/v3/users?domain_id=<my_ldap_domain_id>&enabled=false&name=<myvalidusername>
https://<my_keystone_endpoint>/v3/users?domain_id=<my_ldap_domain_id>&enabled=true&name=<myvalidusername>
```
returns an empty `users: []`, while this:
```
https://<my_keystone_endpoint>/v3/users?domain_id=<my_ldap_domain_id>&name=<myvalidusername>
```
returns the correct user data.

Scanning the  keystone code, I noticed how in https://github.com/openstack/keystone/blob/master/keystone/identity/backends/ldap/core.py#L258 `[user_]enabled_default` seems to be ignored if `[user_]enabled_mask == 0` (the default)

I am not sure about this being the problem, but as a workaround I tried configuring in keystone's domain configuration file:
```
[ldap]
user_enabled_default = 2
user_enabled_mask = 1
```
and the `openstack_identity_user_v3` now works correctly.
