### ISSUE TITLE
Feature request: filtering by metadata in openstack_images_image_v2

### ISSUE THREAD

**Issue by DSpeichert** [terraform-provider-openstack/terraform-provider-openstack#89]
### Affected Resource(s)
- openstack_images_image_v2

### Expected Behavior
Given possible a huge repository of images (e.g. frequently being built, etc.), the metadata is typically used to provide machine-readable facts about images. With the use of certain predefined metadata keys (see [Glance Metadata Catalog](https://docs.openstack.org/glance/latest/user/glancemetadefcatalogapi.html)), it makes sense to describe images by OS, version, flavor and other parameters.

openstack_images_image_v2 aims to find the proper image ID given certain filtering criteria but it does not support filtering by metadata (only by name and tags at the moment).

Since the API does not support filtering by metadata, it can be done client side here, after fetching all matching images (as currently happens) but before evaluating the `most_recent` flag (if enabled).

Given lack of API support at the moment, I suggest only doing simple full match on metadata (no advanced comparisons at this time as it may be eventually supported by Glance API).

### Actual Behavior
openstack_images_image_v2 does not support filtering by metadata

### Important Factoids
- Filtering images by metadata in Glance is not supported by the API. It needs to be done client-side.
- Gophercloud returns metadata information for images

### References
- https://docs.openstack.org/glance/latest/user/glancemetadefcatalogapi.html
- https://docs.openstack.org/image-guide/image-metadata.html

**Comment by jtopjian** [comment]
@DSpeichert Thanks for this. I will take a look and see what we can do.

**Comment by jtopjian** [comment]
@DSpeichert I apologize for the delay on this.

As you've linked, The Glance service provides a metadata service which provides a central repository for metadata. Glance images can contain metadata but they can also store properties and tags. 

Before I started working on this, I wanted to clarify if you're really looking to filter on `metadata` and not `properties`. If it's really metadata, you'll be the first I've run into who has used this feature, so I'll need some help working with it. If you could provide some commands about how to store a piece of metadata and have it show up in an image's result, that should be enough to get me started.

If you want to filter on properties, that's also possible. `properties` is not yet supported in the Terraform resources because it was blocked in Gophercloud. That has now been fixed, so I can look at adding the ability to set and read (and filter) properties in the Terraform Images resources.

**Comment by DSpeichert** [comment]
@jtopjian No problem, I'll try to help out.

First of all, I did some digging into how Gophercloud ([this part](https://github.com/gophercloud/gophercloud/blob/master/openstack/imageservice/v2/images/results.go#L62-L70)) exactly corresponds to how Glance works. Below are just my observations based on reading source code - I haven't had the chance to run it and confirm it right now (it's been a while since I worked with Gophercloud).

### The OpenStack side of things

In OpenStack Glance: "properties" and "metadata" are exactly the same thing. When you GET an image, you get an (almost flat) dict containing everything:
* properties that are always there (have special meaning, e.g.: id, name, created_at)
* properties that may be there and have special meaning but may not be there at all
* metadata (if any) that only administrator can set
* metadata that any user (who is owner of the image) can set

Therefore, there is no way to tell these apart. Clients "know" which keys are "standard" and the server treats everything that it recognizes as "special" in the special way (validating or enforcing read-only) and everything else as-is.

From [API documentation](https://developer.openstack.org/api-ref/image/v2/index.html):
> Another common term for “image properties” is “image metadata”...

### Gophercloud's approach
Based on what I understand from [here](https://github.com/gophercloud/gophercloud/blob/master/openstack/imageservice/v2/images/results.go#L122), the `Image.Properties` dict is populated with every "property" that was not recognized by Gophercloud as something it would assign to the Image type's property. Essentially `Properties` is a catch-all bag.

So what is `Metadata` on the `Image` in Gophercloud? Well, I believe it will always be empty. Unless of course someone puts metadata on the image called literally `metadata`. How someone came up with the distinction between `Properties` and `Metadata` I don't understand, but the Glance API may have simply been confusing.

### Terraform Provider / This PR
Knowing what Gophercloud provides to us, what this PR seeks is filtering by... `Properties` on `Image`, as well as all the actual (statically typed properties). Unfortunately, the `Image.Properties` dict will not have them all anymore (only the unrecognized ones).

I am not sure if that is possible in Terraform (or the way plugins need to be written) but ideally we would accept any keys for image filtering. If a key corresponds to a statically typed property on `Image`, it will be compared. If not, then it will be search for in `Image.Properties`. I am not sure if Terraform would actually expose unexpected keys to this provider even if user specifies them.

### Commands

If you want to play with this, you can execute something like: `glance image-update --property key=value c7caddd3-6f49-4f52-ba2f-3cbdb7a94a1f`. Irony starts here because the CLI calls it "property".

Then you can see that "key" would be returned as part of the dict:
`glance --debug image-show c7caddd3-6f49-4f52-ba2f-3cbdb7a94a1f`

**Comment by jtopjian** [comment]
@DSpeichert Thanks for the detailed reply

> Essentially Properties is a catch-all bag.

This is correct. I was the one who implemented it that way since it seemed like an appropriate approach (until proven otherwise). The other option would have been to parse a schema (which is referenced in the API result) in order to determine which fields were actually properties.

> So what is Metadata on the Image in Gophercloud? Well, I believe it will always be empty. 

This is quite possibly true. 

> but the Glance API may have simply been confusing.

That is most definitely true.

> as well as all the actual (statically typed properties). Unfortunately, the Image.Properties dict will not have them all anymore (only the unrecognized ones).

Can you clarify which properties are the unrecognized ones? You're talking about things like `container_format`, `disk_format`, and all of [these](https://github.com/gophercloud/gophercloud/blob/master/openstack/imageservice/v2/images/results.go#L15-L89)? If so, those can all be added to the Terraform image data source, they will just be distinct parameters. Is that acceptable?

> Commands

Working with `--properties` is what I'm familiar with, so this is all good and that's what I wanted to clarify. Since you linked to the metadata _service_, I wanted to clarify if you were actually utilizing that service or if it was just the `key=value` image property/metadata.

So it looks like there are a few action items I have here:

1. Implement properties in both the Terraform image resource and data source.
2. Implement post-retrieval filtering of properties on the data source _or_ add `Properties` to `images.ListOpts` in Gophercloud.
3. Add the missing static properties to the data source, integrate them into `images.ListOpts` where appropriate.

Let me know if I've missed anything or if something sounds incorrect. Thank you again for the help with this. :)

**Comment by DSpeichert** [comment]
> Can you clarify which properties are the static ones? You're talking about things like container_format, disk_format, and all of these? If so, those can all be added to the Terraform image data source, they will just be distinct parameters. Is that acceptable?

Yes, the ones you referenced are what I refer to as "static" (explicitly defined in Gophercloud on Image type). I don't really care how users will need to specify the filters, as long as they can filter (match) on as many different properties as possible. Not all may make sense but just "in case".

About the metadata service - it's not really a separate service. I believe you are referring to the "metadata catalog". This is just a set few API calls exposing the annotated schema of the metadata. However, it is NOT enforced. You can treat it as "extras". Parsing that is useless because it does not guarantee that properties defined in metadata are actually on images nor the opposite (there may be a property on image that is not in catalog). So all we really want is a blank/wildcard filter-by-anything capability.

Overall, I believe your action items are correct. I wish there was a magic way to make this future-proof and just pass any unrecognized key (whatever user provides), but that probably won't look quite well in statically typed Go.

**Comment by jtopjian** [comment]
@DSpeichert I've done some initial work on this in #113 (properties support). If you're able to test it, let me know what you think.

**Comment by DSpeichert** [comment]
@jtopjian,
Sorry for the delay, I just got a chance to test it.
It is almost what I was hoping for, with one caveat. Right now I see that it will happily pick an image that satisfies **ANY** of the property filters. What I would expect is to only select image/images that satisfy all properties.

**Comment by jtopjian** [comment]
@DSpeichert No problem at all - thanks for testing it out. Good catch! I agree. I'll get this updated soon.

**Comment by jtopjian** [comment]
@DSpeichert I finally had some time to rework this. When you have a moment (no rush), can you try #113 again?

**Comment by DSpeichert** [comment]
@jtopjian It was a pain to test at first for some reasons unknown to me but eventually I got it to work and it works great! I think that's ready. Thanks a lot for working on this.
